[project]
name = "skip-add"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rajesh Venkatesan", email = "rajeshetl78456@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pvporcupine>=4.0.3",
]

[project.scripts]
skip-add = "skip_add:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
